site_name: AcATaMa - Qgis plugin
site_description: AcATaMa is a Qgis plugin for Accuracy Assessment of Thematic Maps
site_author: Xavier Corredor Llano, SMByC-IDEAM
site_favicon: img/favicon.png
site_url: https://smbyc.bitbucket.io/qgisplugins/acatama
repo_url: https://bitbucket.org/smbyc/qgisplugin-acatama
theme:
  name: mkdocs
extra_css:
    - css/extra.css
markdown_extensions:
  - smarty
  - admonition
  - toc:
      permalink: true
  - sane_lists
nav:
  - Home: index.md
  - About: about.md
  - How to use: how_to_use.md
  - Use cases: use_cases.md

