site_name: AcATaMa - Qgis plugin
site_description: AcATaMa is a Qgis plugin for Accuracy Assessment of Thematic Maps
site_author: Xavier Corredor Llano, SMBYC-IDEAM
#site_favicon: favicon_whale.png
site_url: https://smbyc.bitbucket.io/qgisplugins/acatama
repo_url: https://bitbucket.org/smbyc/qgisplugin-acatama
theme: mkdocs
extra_css:
    - css/extra.css
markdown_extensions:
  - smarty
  - admonition
  - toc:
      permalink: true
pages:
- Home: index.md
#- Feature: features.md
- Installation: installation.md
- How to use: how_to_use.md

