name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tags: [ release-3_10, release-3_16, latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Pull QGIS ${{ matrix.docker_tags }}
        run: docker pull qgis/qgis:${{ matrix.docker_tags }}
      # Runs all tests
      - name: Run tests
        run: >
          docker run --rm --net=host -e QGIS_IN_CI=1 --volume `pwd`:/app -w=/app qgis/qgis:${{ matrix.docker_tags }} sh -c
          "pip3 install -qr pytest-qgis fiona shapely && pytest -v --cov --cov-report=xml"

      # Upload coverage report. Will not work if the repo is private
      - name: Upload coverage to Codecov
        if: ${{ matrix.docker_tags == 'latest' && !github.event.repository.private }}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: pytest
          fail_ci_if_error: false # set to true when upload is working
          verbose: false
